### ISSUE TITLE
Setup automatic deployments

### ISSUE THREAD

**Issue by Abbe98** [riksantikvarieambetet/soch-dcat-ap#1]
Travis CI -> Github Pages

https://docs.travis-ci.com/user/cron-jobs/#adding-cron-jobs

**Comment by Abbe98** [comment]
@carwash när man idag uppdateras riksantikvarieambetet/test-leverans-oppnadata.se skördar Öppnadata.se ändringarna automatiskt?

**Comment by carwash** [comment]
Ja. Den skördas om dagligen c.04:00 på natten. Vill man kolla med en gång kan jag logga in och starta skördningen för hand.
